version: "3.8"

services:
  localstack:
    container_name: localstack-task-manager
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # Edge port for all services
      - "4571:4571" # Legacy port
    environment:
      - SERVICES=s3,sqs,sns,dynamodb
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - LS_LOG=warn
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack:/etc/localstack/init/ready.d" # init scripts

